# 배포용 docker-compose.yml

services:
  api-server:
    image: minseok1768/run_api
    container_name: funy-run-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-Dreactor.schedulers.defaultBoundedElasticSize=200"
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - basic
    depends_on:
      - redis

  admin-server:
    image: minseok1768/run_admin
    container_name: funy-run-admin
    environment:
      SPRING_PROFILES_ACTIVE: admin-prod
      JAVA_TOOL_OPTIONS: "-Dreactor.schedulers.defaultBoundedElasticSize=200"
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: always
    networks:
      - basic
    depends_on:
      - redis


  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - basic

networks:
  basic:
    driver: bridge