# 로컬용 docker-compose.yml
services:
  api-server:
    build: ./run_api
    container_name: funy-run-api
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: "-Dreactor.schedulers.defaultBoundedElasticSize=200"
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - basic
    depends_on:
      - redis

  admin-server:
    build: ./run_admin
    container_name: funy-run-admin
    environment:
      SPRING_PROFILES_ACTIVE: admin
      JAVA_TOOL_OPTIONS: "-Dreactor.schedulers.defaultBoundedElasticSize=200"
    env_file:
      - .env
    ports:
      - "8082:8082"
    restart: always
    networks:
      - basic
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - basic

networks:
  basic:
    driver: bridge