services:

 admin-server:
  image: brian506/run_admin:1.0.3
  container_name: admin-api
  env_file:
    - .env.admin
  ports:
    - "8081:8081"
  restart: always
  networks:
    - basic

networks:
  basic:
    driver: bridge